version: "3"

services:
  nginx:
    # depends_on:
    #   - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CERTS_: ${CERTS_}
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

volumes:
  wordpress:

networks:
  network:
    driver: bridge