FROM debian:buster

RUN apt-get update && \ 
	apt-get install -y mariadb-server && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/mysqld \
&& chown -R mysql:mysql /var/run/mysqld \
&& chmod 777 /var/run/mysqld

COPY ./conf/my.cnf /etc/mysql/my.cnf

EXPOSE 3306

# CMD ["tail", "-f", "/dev/null"]
CMD ["mysqld"]
